Добавляет стили на главную: без шапки и футера
kokosmosss/bitrix pull request #2
Opened 2022-12-10 17:52 UTC by kokosmosss

пока у меня неразрешимые вопросы 
- как прибить руку к благотворительности, а то она уезжает при изменении вьюпора.
- что делать с кнопками, которые по макету сильно отличаются или отсутствуют? (я кстати сейчас заметила, что часть кнопок почему то не перенеслась в проект...)
- футер вообще другой - там точно надо блоки местами менять. его наверное не трогать?

2022-12-10 21:48 UTC, wrgraff requested changes

2022-12-10 21:48 UTC, wrgraff commented on source/sass/fonts.scss
> +
Предлагаю сделать 2 шрифта с понятными названиями =)

Можно еще порядок поменять чутка, чтобы шли:
- обычный 400
- обычный 900
- сжатый 400
- сжатый 900

```css
@font-face {
    font-family: 'KFC';
    src:
        url('../fonts/cerakfc-regular.woff2') format('woff2'),
        url('../fonts/cerakfc-regular.woff') format('woff');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'KFC';
    src:
        url('../fonts/cerakfc-black.woff2') format('woff2'),
        url('../fonts/cerakfc-black.woff') format('woff');
    font-weight: 900;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'KFC Condensed';
    src:
        url('../fonts/cerakfc-condensed-regular.woff2') format('woff2'),
        url('../fonts/cerakfc-condensed-regular.woff') format('woff');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'KFC Condensed';
    src:
        url('../fonts/cerakfc-condensed-black.woff2') format('woff2'),
        url('../fonts/cerakfc-condensed-black.woff') format('woff');
    font-weight: 900;
    font-style: normal;
    font-display: swap;
}
```

2022-12-10 21:48 UTC, wrgraff commented on source/index.html
> +
Прелоад можно и не делать, тут на оптимизацию особо рассчитывать не приходится )
Но у нас пускай будет, может и в шаблон сможем внедрить

2022-12-10 21:48 UTC, wrgraff commented on source/sass/blocks/banner.scss
> +    font-family: 'CeraKFC-400';
Нам нужно будет врубить один шрифт для всего сайта.
И по необходимости врубать другой шрифт, который Condensed.

А сами мы только weight менять будем

2022-12-10 21:48 UTC, wrgraff commented on source/sass/blocks/banner.scss
> +.banners-img-with-text-list::before {
Я бы на самом деле предпочел эти руки делать с помощью фона, это было бы проще и управлялось бы из одного места.

2022-12-10 21:48 UTC, wrgraff commented on source/sass/blocks/banner.scss
> +    right: 550px;
Думаю, эта рука должна быть все-таки по центру

```suggestion
    left: calc(50% - 100px);
```

2022-12-10 21:48 UTC, wrgraff commented on source/sass/blocks/banner.scss
> +    transform: rotate(-6deg);
А зачем ты ее крутишь?
Не надо )

2022-12-10 21:48 UTC, arturtrifonov commented on source/sass/blocks/company-item.scss
> +.company-item__text .h4 {
Так там же тег `<h4>`, а не класс
```suggestion
//отлично применяется =)
.company-item__text h4 {
```

2022-12-10 21:48 UTC, arturtrifonov commented on source/sass/blocks/company-item.scss
> +    font-family: 'CeraKFC-400';
Я логику применения семейства шрифтов не очень понимаю у тебя ))

2022-12-10 21:48 UTC, arturtrifonov commented on source/sass/blocks/tizer-bottom.scss
> +    margin-right: auto;
Центрирование через `auto` работает только при наличии ширины, которая как-то определена (максимальная, проценты, еще как-то).

Стоит попробовать установить максимальную ширину и добавить небольшие паддинги по краям, чтобы на более мелких экранах текст не прилипал к краям

2022-12-10 21:48 UTC, arturtrifonov commented on source/sass/blocks/tizer-bottom.scss
> +//тут были попытки поставить фон,
Думаю, я смогу накастовать нам более удобные для перекрытия фоны.
Это тут довольно специфическая задача, придется этим мне заняться или может вместе поработаем над этим

2022-12-11 17:35 UTC, wrgraff approved these changes

2022-12-11 17:35 UTC, wrgraff commented on source/sass/blocks/body.scss
> +        padding-left: 187px;
Какой-то странный отступ, не нравится он мне...

2022-12-11 17:35 UTC, wrgraff commented on source/sass/blocks/buttons.scss
> +//не пойму почему шрифт вот тут не выглядит как в макете, в computed вроде все верно
А мне кажется он так и выглядит как в макете и все у него хорошо )

2022-12-11 17:35 UTC, wrgraff commented on source/sass/blocks/footer.scss
> +//поэтому я взяла из макета подпись около формы в футере и стилизовала также
По-моему, вышло хорошо

2022-12-11 17:35 UTC, wrgraff commented on source/sass/blocks/footer.scss
> +//это импровизация, этого блока нет в макете
Тут я бы так как текст технический оставил бы ему все-таки более обычный шрифт

2022-12-13 16:56 UTC, merged