Volunteering
kokosmosss/bitrix pull request #8
Opened 2022-12-15 12:55 UTC by kokosmosss

Провозилась много с картинкой, но так и не смогла ее прижать к правому краю(
Кнопки я поменяла в разметке.
И еще там где итоги я добавила обертку - гридом сделала, чтобы поставить ровно строки.

2022-12-16 11:02 UTC, wrgraff requested changes
Не буду сам кодить, тут чуток подправить, у тебя все готово считай уже

2022-12-16 11:02 UTC, arturtrifonov commented on source/sass/blocks/company-item.scss
> +.main-item {
Вот в этих айтемах есть <br>, который создает лишние отступы.
Надо или удалять (через бэкендера), или учитывать при создании отступов

2022-12-16 11:02 UTC, arturtrifonov commented on source/sass/blocks/company-item.scss
> +    gap: 50px 10px;
Обрати внимание, что последний `<br>` в самой сетке создает лишний ряд и, как следствие, гэп до него:
<img width="591" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208082455-1b92c03a-f830-4641-8832-2edf4bd87a9f.png">

Нужно опять же или удалять, или возможно безопаснее использовать отступы вместо гэпов.
Сейчас, кстати, есть и то и другое, что не очень хорошо:
<img width="528" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208082705-b3083222-4617-4194-a905-1d0f28ccd66d.png">

2022-12-16 11:02 UTC, arturtrifonov commented on source/sass/blocks/company-item.scss
> +    grid-template-columns: 1fr 1fr;
По-моему, ширина у них не одинакова:
<img width="461" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208083001-c4b6d0f5-a284-49fa-a2bc-0d91b3a1b23d.png">

2022-12-16 11:02 UTC, wrgraff commented on source/sass/blocks/company-item.scss
> +    margin-right: -100%;
Я так понимаю, ты пытаешься придумать такое решение, чтобы картинка стояла так, чтобы всегда примыкать к правому краю.
Не нужно так делать, это не совсем так должно работать =)
Ты усложнила этим себе задачу. Но даже если этого добиться, то как это будет смотреться на очень широком мониторе?

На самом деле, достаточно сделать правый край картинки по максимальной ширине, а не по ширине контента. Для этого подойдет и какой-то фиксированный отступ

2022-12-16 11:02 UTC, wrgraff commented on source/sass/blocks/company-item.scss
> +    @media (max-width: 991px) {
```suggestion
    @media (max-width: 992px) {
```

2022-12-16 11:02 UTC, wrgraff commented on source/sass/blocks/company-item.scss
> +//и на мобиле выглядит не так как надо - вплотную встает к краям
На мобиле надо убрать отрицательные отступы, там картинка вписана в контент

2022-12-16 14:27 UTC, kokosmosss commented on source/sass/blocks/company-item.scss
> +.main-item {
я удалила гэпы у рядов, и маржины у справа.
 по нижнему расстоянию до ссылки (с учетом ее отступа) примерно соответствует макету.

2022-12-16 14:30 UTC, kokosmosss commented on source/sass/blocks/company-item.scss
> +    gap: 50px 10px;
из-за того, что там бр (если его не удалять), 
то только гэпы не очень получается.

2022-12-16 14:30 UTC, kokosmosss commented on source/sass/blocks/company-item.scss
> +    grid-template-columns: 1fr 1fr;
сделала фикс. ширину до 580, после думаю все же лучше равными оставить.

2022-12-17 09:50 UTC, wrgraff approved these changes

2022-12-17 09:50 UTC, merged